#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SITE="https://bukitjalilstadium.com"
PROJECT_URL="https://dash.cloudflare.com/674dbb32223211880bd2173cddf921a7/pages/view/bukitjalilstadium"

TOTAL_STAGES=6
FAILED=()

banner "Cut over to bukitjalilstadium.com"

say "The new site is live at bukitjalilstadium-1ms.pages.dev. This moves the"
say "real domain onto it, points www at the apex, and checks the result."
say ""
note "The old site keeps running until you detach the domain in Stage 2, and the"
note "old project is left untouched afterwards, so rollback is re-attaching the"
note "domain to it."

# check runs one request and reports whether it returned what was expected.
check() {
  local label="$1" expected="$2" url="$3" actual
  actual=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 20 "$url" 2>/dev/null || echo "000")
  if [[ "$actual" == "$expected" ]]; then
    printf '  %s✓%s %-42s %s\n' "$GREEN" "$RESET" "$label" "$actual"
  else
    printf '  %s✗%s %-42s expected %s, got %s\n' "$RED" "$RESET" "$label" "$expected" "$actual"
    FAILED+=("$label (expected $expected, got $actual)")
  fi
}

# check_body looks for a string the new site renders and the old one did not.
check_body() {
  local label="$1" needle="$2" url="$3"
  if curl -sS --max-time 20 "$url" 2>/dev/null | grep -qF "$needle"; then
    printf '  %s✓%s %-42s found\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %-42s not found\n' "$RED" "$RESET" "$label"
    FAILED+=("$label (marker not found)")
  fi
}

pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Find the project serving the live domain"
say "A domain can only be attached to one Pages project, so the old one has to"
say "give it up first. Find which project that is."
open_url "https://dash.cloudflare.com/674dbb32223211880bd2173cddf921a7/pages/view"
step "Look for the project whose Custom domains include bukitjalilstadium.com."
note "  It is the one currently serving the old site. It is NOT"
note "  'bukitjalilstadium', which is the new project."
say ""
ask LEGACY_PROJECT "Type that project's name (for the rollback note):"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Move the apex domain"
warn "This is the step that takes the old site off the air. Do the two halves"
warn "back to back: Cloudflare keeps the DNS record, so the gap is seconds."
say ""
step "On the OLD project: Settings -> Custom domains -> remove bukitjalilstadium.com."
say ""
step "On the NEW project (bukitjalilstadium): Settings -> Custom domains ->"
step "  Add -> Custom domain -> bukitjalilstadium.com."
note "  Accept the DNS record it offers to create if asked."
pause "Press Enter once the new project lists the domain as active."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Redirect www to the apex"
say "The apex is canonical, so www has to redirect to it. A Pages _redirects"
say "file cannot redirect across hosts, so this belongs in a zone rule."
open_url "https://dash.cloudflare.com/674dbb32223211880bd2173cddf921a7/bukitjalilstadium.com/rules/redirect-rules"
step "Create a Redirect Rule:"
note "    When incoming requests match:  Hostname equals www.bukitjalilstadium.com"
note "    Then redirect to:              https://bukitjalilstadium.com"
note "    with:                          Dynamic -> concat(\"https://bukitjalilstadium.com\", http.request.uri.path)"
note "    Status code:                   301"
note "    Preserve query string:         ON  (otherwise a www link carrying"
note "                                       ?section=... loses the Section)"
step "Save and deploy."
say ""
warn "For the rule to fire, www must be proxied through Cloudflare. If"
warn "www.bukitjalilstadium.com does not resolve, add a proxied record for it"
warn "under DNS first."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Enable Cloudflare Web Analytics"
say "The self-hosted Umami tracker is already in the code. This is the second"
say "tracker, and it needs no code: Cloudflare injects its beacon, and only for"
say "the production domain, so previews stay out of it."
open_url "$PROJECT_URL"
step "Open the project, find Web Analytics, and enable it for this project."
pause "Press Enter once it is on."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the live domain"
say "Checking the things that would be wrong if the cutover half-worked."
say ""
check "apex serves the site"                "200" "$SITE/"
check_body "apex is the new site" "Stadium Bukit Jalil (TM Stadium Nasional) Seating View" "$SITE/"
check "a Section page, no redirect"        "200" "$SITE/101"
check "a Section page with a slash"        "308" "$SITE/101/"
check "the 404 page"                       "404" "$SITE/does-not-exist"
check "the contribute form"                "200" "$SITE/contribute"
check "the sitemap"                        "200" "$SITE/sitemap.xml"
check "robots"                             "200" "$SITE/robots.txt"
check "www redirects to the apex"          "301" "https://www.bukitjalilstadium.com/"
say ""
step "Also open the site in a browser and click a Section, then a photo, and"
step "confirm the console has no errors:"
open_url "$SITE"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Rollback"
say "Nothing was deleted, so rollback is one step:"
step "Re-attach bukitjalilstadium.com to $LEGACY_PROJECT, and remove it from the new project."
note "  The old project still holds its last deployment, and the new project"
note "  keeps its pages.dev URL either way."
say ""
step "When you are confident, the legacy directory can be deleted from the"
step "repository as a separate change. That is the last piece of the migration."
pause "Press Enter to finish."

finish
