#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$APP_DIR/.dev.vars"
REPO="afrieirham/bukitjalilstadium"

# If anything unexpected fails, name the line instead of exiting quietly.
trap 'printf "\n  ✗ failed at line %s: %s\n" "$LINENO" "$BASH_COMMAND" >&2' ERR

TOTAL_STAGES=6

banner "Watermark credentials"

say "The watermark runs as a GitHub Action when a Contribution merges. It needs"
say "four repository secrets for an R2 token, and a GitHub credential that is"
say "allowed to edit workflow files. This wizard gathers both."
say ""
note "It writes the values to new/.dev.vars (git-ignored) and sets them as"
note "repository secrets, so re-running it is safe."
pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "GitHub CLI: allow workflow changes"
say "Pushing .github/workflows/watermark.yml needs the 'workflow' scope, which"
say "this token does not have yet. This opens a browser to grant it."
say ""
step "Running: gh auth refresh -h github.com -s workflow"
if command -v gh >/dev/null 2>&1; then
  if gh auth refresh -h github.com -s workflow; then
    note "  ✓ the 'workflow' scope is granted"
  else
    warn "could not refresh; run it yourself: gh auth refresh -h github.com -s workflow"
    SKIPPED+=("grant the 'workflow' scope to gh")
  fi
else
  warn "gh is not installed; install it, then run: gh auth refresh -h github.com -s workflow"
  SKIPPED+=("install gh and grant it the 'workflow' scope")
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: the account and the bucket"
say "The Action talks to R2 through its S3 API, so it needs the account ID and"
say "the bucket name."
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "Copy the Account ID, shown on the right of the R2 overview."
ask R2_ACCOUNT_ID "Paste the Account ID:"
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
step "Find the bucket behind storage.bukitjalilstadium.com and copy its name."
note "  If several look plausible, open each bucket's Settings and check which one"
note "  has the custom domain storage.bukitjalilstadium.com attached."
ask R2_BUCKET "Paste the bucket name:"
write_env R2_BUCKET "$R2_BUCKET"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: an R2 API token"
say "This token can read and write objects in the one bucket, and nothing else."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Choose 'Create API token'."
step "Name it something like 'bukitjalilstadium watermark'."
step "Permissions: 'Object Read & Write'."
step "Scope it to the bucket from Stage 2 (or all buckets, if the picker is fiddly)."
step "Create it, then copy the Access Key ID and the Secret Access Key."
warn "The Secret Access Key is shown once. Copy it before you close the page."
say ""
ask R2_ACCESS_KEY_ID "Paste the Access Key ID:"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key:"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub: the four repository secrets"
say "These are exactly the secrets .github/workflows/watermark.yml reads."
set_secret R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
set_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
set_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
set_secret R2_BUCKET "$R2_BUCKET"
say ""
note "They are also in $ENV_FILE, so the tool can be run by hand for a test."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Publish the Action"
say "The Action only runs once .github/workflows/watermark.yml is on GitHub."
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [[ -z "$BRANCH" || "$BRANCH" == "HEAD" ]]; then
  warn "not on a branch in a git checkout, so nothing was pushed."
  SKIPPED+=("push the branch that carries .github/workflows/watermark.yml")
else
  if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1 \
    && [[ -z "$(git log "origin/$BRANCH..$BRANCH" --oneline 2>/dev/null)" ]]; then
    note "  $BRANCH is already up to date on origin"
  elif confirm "Push $BRANCH to origin now?"; then
    if git push -u origin "$BRANCH"; then
      note "  ✓ pushed $BRANCH"
    else
      warn "push failed; if it mentions the 'workflow' scope, redo Stage 1."
      SKIPPED+=("push $BRANCH")
    fi
  else
    SKIPPED+=("push $BRANCH")
  fi

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    EXISTING_PR="$(gh pr list --repo "$REPO" --head "$BRANCH" --state open --json url --jq '.[0].url' 2>/dev/null || true)"
    if [[ -n "$EXISTING_PR" ]]; then
      note "  pull request already open: $EXISTING_PR"
    elif confirm "Open a pull request for $BRANCH?"; then
      if gh pr create --repo "$REPO" --base main --head "$BRANCH" \
        --title "feat: watermark new Contribution photos at publish" \
        --body "Publish-time watermarking for new Contribution photos. See docs/adr/0005-watermark-at-publish.md."; then
        note "  ✓ opened the pull request"
      else
        warn "could not open the pull request; open one from the compare page."
        SKIPPED+=("open the pull request")
      fi
    fi
  fi
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "After the next Contribution merges, the Action runs. Watch it with:"
note "  gh run list --repo $REPO --workflow watermark.yml --limit 5"
note "  gh run watch --repo $REPO"
say ""
say "Confirm the secrets landed:"
note "  gh secret list --repo $REPO"
say ""
warn "Only new photos are watermarked. The legacy seats/* photos are left as they are."

finish
