#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$APP_DIR/.dev.vars"

# If anything unexpected fails, name the line instead of exiting quietly.
trap 'printf "\n  ✗ failed at line %s: %s\n" "$LINENO" "$BASH_COMMAND" >&2' ERR

TOTAL_STAGES=8

banner "Contribution credentials"

say "This wires up everything the /contribute form needs: a bot challenge, a"
say "place to put photos, a counter for the rate limit, and permission to open"
say "a pull request for review."
say ""
note "This project is configured by new/wrangler.jsonc. Cloudflare therefore"
note "treats that file as the source of truth: bindings and plain variables are"
note "set there in the repo, and only Secrets can be set in the dashboard."
pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Turnstile: create the widget"
say "Turnstile is the bot challenge on the form. It is free."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Choose 'Add widget', name it something like 'Bukit Jalil Stadium contribute'."
step "Add these hostnames, or the widget will refuse to run:"
note "    bukitjalilstadium-1ms.pages.dev   (the project's own domain)"
note "    bukitjalilstadium.com             (the custom domain, once cut over)"
step "Save, then copy the Site Key (public) and the Secret Key (private)."
say ""
ask TURNSTILE_SITE_KEY "Paste the Site Key:"
write_env TURNSTILE_SITE_KEY "$TURNSTILE_SITE_KEY"
ask_secret TURNSTILE_SECRET "Paste the Secret Key:"
write_env TURNSTILE_SECRET "$TURNSTILE_SECRET"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "R2: find the photos bucket"
say "Photos stay in the bucket you already serve from storage.bukitjalilstadium.com."
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "Find the bucket behind that custom domain and copy its name."
note "  If several look plausible, open each bucket's Settings and check which one"
note "  has the custom domain storage.bukitjalilstadium.com attached."
ask R2_BUCKET "Paste the bucket name:"
write_env R2_BUCKET "$R2_BUCKET"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "KV: create the rate-limit namespace"
say "A small counter per visitor per hour. Also free."
open_url "https://dash.cloudflare.com/?to=/:account/workers/kv/namespaces"
step "Create an instance named bukitjalilstadium-rate-limit (any name will do)."
step "Open it and copy the ID."
ask RATE_LIMIT_ID "Paste the namespace ID:"
write_env RATE_LIMIT_ID "$RATE_LIMIT_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub: a token that can open pull requests"
say "A fine-grained token, limited to this one repository, so the site can file a"
say "Contribution for review and nothing else."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: anything, e.g. 'bukitjalilstadium contribute'."
step "Expiration: pick something you will remember to renew."
step "Repository access: 'Only select repositories' -> afrieirham/bukitjalilstadium."
step "Permissions: Contents -> Read and write; Pull requests -> Read and write."
note "  Metadata read is added automatically and is required."
step "Generate the token and copy it."
ask_secret GITHUB_TOKEN "Paste the token:"
write_env GITHUB_TOKEN "$GITHUB_TOKEN"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pages: the two secrets"
say "Secrets are the only thing the dashboard can still manage on this project,"
say "because wrangler.jsonc owns everything else."
open_url "https://dash.cloudflare.com/674dbb32223211880bd2173cddf921a7/pages/view/bukitjalilstadium"
step "Open Settings, then Variables and Secrets."
step "Add a Secret named TURNSTILE_SECRET, for both Production and Preview."
note "    value: the Secret Key from Stage 1 (also saved in new/.dev.vars)"
step "Add a Secret named GITHUB_TOKEN, for both environments."
note "    value: the token from Stage 4 (also saved in new/.dev.vars)"
warn "Do not try to add BUCKET, RATE_LIMIT or a site key here: this project's"
warn "bindings and plain variables come from the repository instead."
pause "Press Enter once both secrets are saved."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Repository: the bindings and the site key"
say "Writing the bucket, the namespace and the site key into new/wrangler.jsonc."
say "None of these are secret, and keeping them in git is what makes the"
say "configuration reviewable."

say "Patching $APP_DIR/wrangler.jsonc"

patch_wrangler_config() {
  node - "$APP_DIR/wrangler.jsonc" "$TURNSTILE_SITE_KEY" "$R2_BUCKET" "$RATE_LIMIT_ID" <<'NODE'
const { readFileSync, writeFileSync } = require("node:fs");

const [file, siteKey, bucket, kvId] = process.argv.slice(2);
let text = readFileSync(file, "utf8");

const keyPattern = /("TURNSTILE_SITE_KEY":\s*)"[^"]*"/;
if (!keyPattern.test(text)) throw new Error("TURNSTILE_SITE_KEY is missing from wrangler.jsonc");
text = text.replace(keyPattern, `$1${JSON.stringify(siteKey)}`);

// Drop any binding lines from a previous run, then insert fresh ones after
// compatibility_date, which is where the comma already is.
const lines = text
  .split("\n")
  .filter((line) => {
    const bare = line.replace(/^\s*\/\/\s*/, "").trim();
    return !bare.startsWith('"r2_buckets"') && !bare.startsWith('"kv_namespaces"');
  });

const anchor = lines.findIndex((line) => line.includes('"compatibility_date"'));
if (anchor === -1) throw new Error("compatibility_date is missing from wrangler.jsonc");
if (!lines[anchor].trimEnd().endsWith(",")) throw new Error("compatibility_date needs a trailing comma");

lines.splice(
  anchor + 1,
  0,
  `  "r2_buckets": [{ "binding": "BUCKET", "bucket_name": ${JSON.stringify(bucket)} }],`,
  `  "kv_namespaces": [{ "binding": "RATE_LIMIT", "id": ${JSON.stringify(kvId)} }],`,
);
text = lines.join("\n");

// The file is JSON with // comments, so strip those and prove it still parses.
const parsed = JSON.parse(text.replace(/^\s*\/\/.*$/gm, ""));
if (parsed.vars.TURNSTILE_SITE_KEY !== siteKey) throw new Error("site key did not land");
if (parsed.r2_buckets[0].bucket_name !== bucket) throw new Error("bucket did not land");
if (parsed.kv_namespaces[0].id !== kvId) throw new Error("namespace id did not land");

writeFileSync(file, text);
console.log("  validated new/wrangler.jsonc");
NODE
}

show_bindings_snippet() {
  say "Add these to new/wrangler.jsonc, just after compatibility_date:"
  note "  \"r2_buckets\": [{ \"binding\": \"BUCKET\", \"bucket_name\": \"$R2_BUCKET\" }],"
  note "  \"kv_namespaces\": [{ \"binding\": \"RATE_LIMIT\", \"id\": \"$RATE_LIMIT_ID\" }],"
  say "and set this value in the same file:"
  note "  \"TURNSTILE_SITE_KEY\": \"$TURNSTILE_SITE_KEY\""
}

if [[ ! -f "$APP_DIR/wrangler.jsonc" ]]; then
  warn "new/wrangler.jsonc is missing, so it was left alone."
  show_bindings_snippet
  SKIPPED+=("write the bindings into new/wrangler.jsonc")
elif ! command -v node >/dev/null 2>&1; then
  warn "node is not on PATH, so new/wrangler.jsonc was left alone."
  show_bindings_snippet
  SKIPPED+=("write the bindings into new/wrangler.jsonc")
elif patch_wrangler_config; then
  note "  wrote new/wrangler.jsonc"
else
  warn "could not edit new/wrangler.jsonc automatically."
  show_bindings_snippet
  SKIPPED+=("write the bindings into new/wrangler.jsonc")
fi

say ""
step "Commit and push, so Pages picks the configuration up:"
note "    git add new/wrangler.jsonc"
note "    git commit -m 'chore: connect the contribute bindings'"
note "    git push"
warn "Until this is pushed, the deployed site still has no bucket or counter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Local development file"
say "Writing the same values plus the secrets to new/.dev.vars, which wrangler"
say "reads for local development. It is git-ignored."
write_env TURNSTILE_SECRET "$TURNSTILE_SECRET"
write_env TURNSTILE_SITE_KEY "$TURNSTILE_SITE_KEY"
write_env GITHUB_TOKEN "$GITHUB_TOKEN"
write_env R2_BUCKET "$R2_BUCKET"
write_env RATE_LIMIT_ID "$RATE_LIMIT_ID"
if grep -qE '^\.dev\.vars$' "$APP_DIR/.gitignore" 2>/dev/null; then
  note "  .dev.vars is already ignored by git."
else
  warn "add .dev.vars to new/.gitignore before committing anything"
  SKIPPED+=("add .dev.vars to new/.gitignore")
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Wait for the deployment that your push triggered, then check three things."
say ""
step "1. The public site key is being served:"
note "    curl -sS https://bukitjalilstadium-1ms.pages.dev/api/config"
note "    expect {\"turnstileSiteKey\":\"<your site key>\"}"
say ""
step "2. A submission is refused for the right reason:"
note "    curl -sS -X POST https://bukitjalilstadium-1ms.pages.dev/api/photos \\"
note "      -F photo=@some.jpg -F turnstileToken=nonsense -w ' %{http_code}\\n'"
note "    expect 403 'could not confirm you are human'."
note "    A 503 means a secret or binding is still missing."
say ""
step "3. Submit a real Contribution from the site and confirm the pull request"
step "   appears. Close that test pull request instead of merging it."
open_url "https://bukitjalilstadium-1ms.pages.dev/contribute"

finish
