#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Contribution credentials"

say "This wires up everything the /contribute form needs: a bot challenge, a"
say "place to put photos, a counter for the rate limit, and permission to open"
say "a pull request for review. Nothing here is committed to the repo."
pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Turnstile: create the widget"
say "Turnstile is the bot challenge on the form. It is free."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Choose 'Add widget', name it something like 'Bukit Jalil Stadium contribute'."
step "Add these hostnames, or the widget will refuse to run:"
note "    bukitjalilstadium-1ms.pages.dev   (the project's own domain)"
note "    bukitjalilstadium.com             (the custom domain, once cut over)"
step "Save, then copy the Site Key (public) and the Secret Key (private)."
say ""
ask TURNSTILE_SITE_KEY "Paste the Site Key:"
ask_secret TURNSTILE_SECRET "Paste the Secret Key:"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "R2: find the photos bucket"
say "Photos stay in the bucket you already serve from storage.bukitjalilstadium.com."
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "Find the bucket behind that custom domain and copy its name."
note "  If several look plausible, open each bucket's Settings and check which one"
note "  has the custom domain storage.bukitjalilstadium.com attached."
ask R2_BUCKET "Paste the bucket name:"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "KV: create the rate-limit namespace"
say "A small counter per visitor per hour. Also free."
open_url "https://dash.cloudflare.com/?to=/:account/workers/kv/namespaces"
step "Create an instance named bukitjalilstadium-rate-limit (any name will do)."
step "Open it and copy the ID."
ask RATE_LIMIT_ID "Paste the namespace ID:"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub: a token that can open pull requests"
say "A fine-grained token, limited to this one repository, so the site can file a"
say "Contribution for review and nothing else."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: anything, e.g. 'bukitjalilstadium contribute'."
step "Expiration: pick something you will remember to renew."
step "Repository access: 'Only select repositories' -> afrieirham/bukitjalilstadium."
step "Permissions: Contents -> Read and write; Pull requests -> Read and write."
note "  Metadata read is added automatically and is required."
step "Generate the token and copy it."
ask_secret GITHUB_TOKEN "Paste the token:"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pages: variables and secrets"
say "Now put the values on the Pages project. Settings -> Variables and Secrets."
open_url "https://dash.cloudflare.com/674dbb32223211880bd2173cddf921a7/pages/view/bukitjalilstadium"
step "Add a plain variable VITE_TURNSTILE_SITE_KEY, for both Production and Preview."
note "    value: the public Site Key from Stage 1"
step "Add a secret TURNSTILE_SECRET, for both environments."
note "    value: the Secret Key from Stage 1 (it is also in new/.dev.vars)"
step "Add a secret GITHUB_TOKEN, for both environments."
note "    value: the token from Stage 4 (it is also in new/.dev.vars)"
warn "The dashboard labels move around; if you cannot find these, look for"
warn "'Environment variables' or 'Variables and Secrets' in the project settings."
pause "Press Enter once all three are saved."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Pages: bindings"
say "Bindings are how the Function reaches the bucket and the counter."
step "In the same project, find Bindings (Settings -> Bindings)."
step "Add an R2 bucket binding with the variable name exactly: BUCKET"
note "    bucket: the name from Stage 2"
step "Add a KV namespace binding with the variable name exactly: RATE_LIMIT"
note "    namespace: the one from Stage 3"
pause "Press Enter once both bindings are saved."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Local development files"
say "Writing the values you entered to two local files so wrangler pages dev and"
say "npm run dev can reach the real services. Neither file belongs in git."
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$APP_DIR/.dev.vars"
write_env TURNSTILE_SECRET "$TURNSTILE_SECRET"
write_env GITHUB_TOKEN "$GITHUB_TOKEN"
write_env R2_BUCKET "$R2_BUCKET"
write_env RATE_LIMIT_ID "$RATE_LIMIT_ID"
ENV_FILE="$APP_DIR/.env"
write_env VITE_TURNSTILE_SITE_KEY "$TURNSTILE_SITE_KEY"
ENV_FILE="$APP_DIR/.dev.vars"

printf '  %s✓ wrote%s VITE_TURNSTILE_SITE_KEY → %s\n' "$GREEN" "$RESET" "$APP_DIR/.env"
if grep -qE '^/?\.dev\.vars$' "$APP_DIR/.gitignore" 2>/dev/null; then
  note "  .dev.vars is already ignored by git."
else
  warn "add .dev.vars to new/.gitignore before committing anything"
  SKIPPED+=("add .dev.vars to new/.gitignore")
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Trigger a fresh deployment so the new variables and bindings take effect:"
step "In the Pages project, choose 'Retry deployment', or push any commit."
say ""
say "Then check the endpoint reports a challenge failure rather than a"
say "configuration failure. A 503 means a binding or secret is still missing;"
say "a 403 for a made-up token means everything is wired."
step "Run:"
note "    curl -sS -X POST https://bukitjalilstadium-1ms.pages.dev/api/photos \\"
note "      -F photo=@some.jpg -F turnstileToken=nonsense -w ' %{http_code}\\n'"
say ""
say "Expected: {\"error\":\"We could not confirm you are human...\"} 403"
say ""
say "Finally, open the site, submit a real Contribution, and confirm the pull"
say "request appears in the repository. Delete that test contribution before"
say "merging it."
open_url "https://bukitjalilstadium-1ms.pages.dev/contribute"

finish
